#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Install IngeCAD into the user's desktop environment (launcher, icon,
# .dwg/.dxf file association). Safe to re-run after updating the icon.
#
# GNOME Shell only re-reads desktop entries and icons at login: after the
# FIRST install (or an icon change) log out and back in to see the icon.
set -e

HERE=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
BIN="$HOME/.local/bin"
APPS="$HOME/.local/share/applications"
ICONS="$HOME/.local/share/icons/hicolor"
mkdir -p "$BIN" "$APPS" "$ICONS/scalable/apps"

# Launcher script (venv python, repo main.py).
cat > "$BIN/ingecad" <<SH
#!/bin/sh
# IngeCAD launcher (generated by scripts/install-desktop.sh).
exec "$HERE/venv/bin/python" "$HERE/main.py" "\$@"
SH
chmod +x "$BIN/ingecad"

# Desktop entry with an absolute Exec (~/.local/bin may not be in PATH for
# the session that spawns GNOME Shell).
sed "s|^Exec=.*|Exec=$BIN/ingecad %f|" \
    "$HERE/resources/ingecad.desktop" > "$APPS/ingecad.desktop"

# Icon: the scalable SVG plus rasterized sizes. GNOME's icon cache prefers
# pre-rasterized PNGs; regenerating them here keeps every size in sync with
# resources/ingecad.svg.
cp "$HERE/resources/ingecad.svg" "$ICONS/scalable/apps/ingecad.svg"
for s in 16 24 32 48 64 128 256 512; do
    mkdir -p "$ICONS/${s}x${s}/apps"
    if command -v rsvg-convert >/dev/null 2>&1; then
        rsvg-convert -w "$s" -h "$s" "$HERE/resources/ingecad.svg" \
            -o "$ICONS/${s}x${s}/apps/ingecad.png"
    elif command -v inkscape >/dev/null 2>&1; then
        inkscape -w "$s" -h "$s" "$HERE/resources/ingecad.svg" \
            -o "$ICONS/${s}x${s}/apps/ingecad.png" >/dev/null 2>&1
    fi
done

command -v gtk-update-icon-cache >/dev/null 2>&1 \
    && gtk-update-icon-cache -f "$ICONS" >/dev/null 2>&1 || true
command -v update-desktop-database >/dev/null 2>&1 \
    && update-desktop-database "$APPS" || true
if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default ingecad.desktop image/vnd.dwg || true
    xdg-mime default ingecad.desktop image/vnd.dxf || true
fi

echo "IngeCAD installed:"
echo "  launcher : $BIN/ingecad"
echo "  desktop  : $APPS/ingecad.desktop"
echo "  icons    : $ICONS/*/apps/ingecad.*"
echo "If the launcher icon does not show yet, log out and back in"
echo "(GNOME Shell only refreshes desktop entries/icons at login)."
